{{- if .Values.istio.enabled }}
apiVersion: {{ .Values.istio.apiVersion }}
kind: VirtualService
metadata:
  name: {{ include "jxpipelines.fullname" $ }}
spec:
  gateways:
{{- if .Values.istio.createGateway }}
  - jx-gateway
{{- else }}
  - {{ .Values.istio.gateway.name }}
{{- end }}
  hosts:
  - dashboard{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  http:
  - route:
    - destination:
        host: {{ include "jxpipelines.fullname" $ }}
      weight: 100
{{- end }}
